CREATE TABLE IF NOT EXISTS areas (
    id INT unsigned AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    view_flg tinyint unsigned DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);