name: Static Analysis

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/static_analysis.yml'
      - 'src/**'

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Actions Timeline
      uses: Kesin11/actions-timeline@v2

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, zip, xml

    - name: Get Composer Cache Directory
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vendor
        key: "php-74-static-analysis-composer-${{ hashFiles('composer.json') }}"
        restore-keys: "php-74-static-analysis-composer-"

    - name: Laravel Install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        composer install

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libonig-dev libzip-dev unzip libxml2 zlib1g-dev

    - name: Run Static Analysis
      run: |
        php vendor/bin/phpstan analyse -l 5 src/
